name: CI

on:
  - push
  - pull_request

jobs:
  ci:
    name: Lint and Test with Node.js ${{ matrix.node }} on ${{ matrix.os }}
    strategy:
      matrix:
        node:
          - 14
          - 16
          - 18
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Link Yarn global binaries into PATH
        run: echo "$(yarn global bin)" >> $GITHUB_PATH

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Build, Lint and test
        run: |
          yarn test
          yarn lint
        env:
          EFF_NO_LINK_RULES: true
          PARSER_NO_WATCH: true

      - name: Benchmark
        run: yarn benchmark

      - name: Codecov
        run: |
          yarn global add codecov codacy-coverage
          codecov
          cat ./coverage/lcov.info | codacy-coverage -u rx-ts -n synckit
        env:
          CI: 'true'
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          CODACY_ACCOUNT_TOKEN: ${{ secrets.CODACY_ACCOUNT_TOKEN }}
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
